name: AutoReplant
version: ${project.version}
description: Automatically replants crops when harvested with specific tools.
main: me.niko302.autoreplant.AutoReplant
api-version: '1.20'
authors: [ Niko302, BitByLogic ]

commands:
  autoreplant:
    description: 'Toggle autoreplant feature'
    usage: /autoreplant
    permission: autoreplant.use

permissions:
  autoreplant.use:
    description: Allows use of the autoreplant command
    default: op
  autoreplant.ignoretoolrestrictions:
    description: Allows ignoring tool restrictions for autoreplant
    default: false